images:
  accounting:
    action: CREATE
    repo_path: src/accounting
    docker_file: Dockerfile
    image_tag: v2
  ad:
    action: CREATE
    repo_path: src/ad
    docker_file: Dockerfile
    image_tag: v1